spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        authorization-clients:
          graph:
            scopes: https://graph.microsoft.com/User.Read



         